language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

addons:
  sonarcloud:
    organization: "baskloosterman-github"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

# command to run tests
script:
  - pytest --cov-report=xml --cov=medmij_oauth tests/
  - sonar-scanner